ALTER TABLE [dbo].[SEL01_PUESTOS_POS] DROP CONSTRAINT [FK_SEL01_PUESTOS_POS_SEL10_PUESTOS]
GO

ALTER TABLE [dbo].[SEL01_PUESTOS_POS] ADD CONSTRAINT [FK_SEL01_PUESTOS_POS_SEL10_PUESTOS] FOREIGN KEY 
	(
		[oi_puesto]
	) REFERENCES [ORG04_PUESTOS] (
		[oi_puesto]
	)
GO    
         
         
         
         
ALTER TABLE [dbo].[SEL02_REFERENCIAS] DROP CONSTRAINT [FK_SEL02_RE_POSICION__SEL10_PO]

GO

ALTER TABLE [dbo].[SEL02_REFERENCIAS] ADD CONSTRAINT [FK_SEL02_RE_POSICION__SEL10_PO] FOREIGN KEY 
	(
		[oi_posicion]
	) REFERENCES [ORG04_POSICIONES] (
		[oi_posicion]
	)
GO
         
         
         
         
         
ALTER TABLE [dbo].[SEL02_REFERENCIAS] DROP CONSTRAINT [FK_SEL02_RE_PUESTO_RE_SEL10_PU]

GO

ALTER TABLE [dbo].[SEL02_REFERENCIAS] ADD CONSTRAINT [FK_SEL02_RE_PUESTO_RE_SEL10_PU] FOREIGN KEY 
	(
		[oi_puesto]
	) REFERENCES [ORG04_PUESTOS] (
		[oi_puesto]
	)
GO

    
ALTER TABLE [dbo].[SEL09_PERS_POSIC] DROP CONSTRAINT [FK_SEL09_PERS_POSIC_SEL10_POSICIONES]

GO
ALTER TABLE [dbo].[SEL09_PERS_POSIC] ADD CONSTRAINT [FK_SEL09_PERS_POSIC_SEL10_POSICIONES] FOREIGN KEY 
	(
		[oi_posicion]
	) REFERENCES [ORG04_POSICIONES] (
		[oi_posicion]
	)
GO
 

ALTER TABLE [dbo].[SEL09_PERS_PUESTO] DROP CONSTRAINT [FK_SEL09_PERS_PUESTO_SEL10_PUESTOS]

GO
ALTER TABLE [dbo].[SEL09_PERS_PUESTO] ADD CONSTRAINT [FK_SEL09_PERS_PUESTO_SEL10_PUESTOS] FOREIGN KEY 
	(
		[oi_puesto]
	) REFERENCES [ORG04_PUESTOS] (
		[oi_puesto]
	)
GO



ALTER TABLE [dbo].[SEL01_POSICION_POS] DROP CONSTRAINT [FK_SEL01_POSICION_POS_SEL10_POSICIONES]

GO
ALTER TABLE [dbo].[SEL01_POSICION_POS] ADD CONSTRAINT [FK_SEL01_POSICION_POS_SEL10_POSICIONES] FOREIGN KEY 
	(
		[oi_posicion]
	) REFERENCES [ORG04_POSICIONES] (
		[oi_posicion]
	)
GO








