ALTER TABLE POS01_LIB_SANIT
DROP CONSTRAINT AK_KEY_2_POS01_LI

ALTER TABLE POS01_LIB_SANIT
ALTER COLUMN e_lib_sanit INT NULL

ALTER TABLE POS01_LIB_SANIT
ALTER COLUMN f_vencimiento DATETIME NULL

ALTER TABLE POS01_LIB_SANIT
ALTER COLUMN d_autoridad VARCHAR(100) NULL