ALTER TABLE [dbo].[ORG03_UBICACIONES] DROP CONSTRAINT [AK_AK1_ORG_UBICACIONE_ORG03_UB] 
GO

ALTER TABLE [dbo].[ORG03_UBICACIONES] ADD CONSTRAINT [AK_AK1_ORG_UBICACIONE_ORG03_UB] UNIQUE  NONCLUSTERED
	(
		[oi_empresa], [c_ubicacion]
	)  ON [PRIMARY] 
GO