ALTER TABLE POS01_DOCUM_CV
DROP CONSTRAINT AK_POS01_DOCUM_POS
ALTER TABLE POS01_DOMIC_CV
DROP CONSTRAINT AK_POS01_DOMIC_POS
ALTER TABLE POS01_COMPET_CV
DROP CONSTRAINT AK_COMPETENCIA_POS
ALTER TABLE POS01_FLIARES_CV
DROP CONSTRAINT AK_POS_FAMILIARES_POS
ALTER TABLE POS01_IDIOMAS_CV
DROP CONSTRAINT AK_POS_IDIOMAS_POS
ALTER TABLE POS01_ESTUDIOS_CV
DROP CONSTRAINT AK_POS01_ESTUDIOS_POS


ALTER TABLE POS01_CURSOS_CV 
ADD CONSTRAINT AK_AK_POS01_CURSOS_POS01_CU UNIQUE (oi_cv, oi_curso, d_curso_ext_cv)
GO

ALTER TABLE POS01_DOCUM_CV 
ADD CONSTRAINT AK_POS01_DOCUM_POS unique (oi_cv, oi_tipo_documento)
GO

ALTER TABLE POS01_DOMIC_CV
ADD CONSTRAINT AK_POS01_DOMIC_POS unique (oi_cv, oi_tipo_domicilio)
GO

ALTER TABLE POS01_COMPET_CV
ADD CONSTRAINT AK_COMPETENCIA_POS unique (oi_cv, oi_competencia)
GO

ALTER TABLE POS01_FLIARES_CV
ADD CONSTRAINT AK_POS_FAMILIARES_POS unique (oi_cv, oi_tipo_documento, c_nro_documento)
GO

ALTER TABLE POS01_IDIOMAS_CV
ADD CONSTRAINT AK_POS_IDIOMAS_POS unique (oi_cv, oi_idioma)
GO

ALTER TABLE POS01_LIB_SANIT
ADD CONSTRAINT AK_KEY_2_POS01_LI unique (oi_cv, c_tipo_lib)
GO

ALTER TABLE POS01_ESTUDIOS_CV 
ADD CONSTRAINT AK_POS01_ESTUDIOS_POS UNIQUE (oi_cv, oi_estudio)
GO